// Layout component for the app
import type { Metadata } from "next";
// fonts
import { Inter } from "next/font/google";
// components
import Header from "@/components/Header";
import Footer from "@/components/Footer";
// styles
import "./globals.css";
import "../styles/bootstrap.min.css";
import "../styles/util.css";
import "../styles/main.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "COZA STORE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
